server:
  port: 8080
file.system.storage:
  path: "J:/JAVA/JTM_fsss"
spring.h2.console.enabled: true
spring.jpa.hibernate.ddl-auto: create-drop
logging:
  level:
    org.springframework.jdbc.core: DEBUG
spring:
  jpa:
    show-sql: true

---
spring.profiles: dev
server:
  port: 8080
file.system.storage:
  path: "J:/JAVA/JTM_fsss"

spring.h2.console.enabled: true
spring.jpa.hibernate.ddl-auto: create-drop

logging:
  level:
    org.springframework.jdbc.core: DEBUG

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
---
spring.profiles: prod
server:
  port: 9090
file.system.storage:
  path: "J:/JAVA/JTM_fsss"
spring:
  jpa:
    show-sql: true
