server:
  port: 8080

app.task:
  endpointMessage: Hello, world!

---
spring.profiles: dev
server:
  port: 8080
file.system.storage:
  path: "C:/Users/agruszczewski/Documents/JTM"

spring:
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.jdbc.core: DEBUG
---
spring.profiles: prod
server:
  port: 9090
file.system.storage:
  path: "J:/JAVA/JTM_fsss"