server:
  port: 8080

app.task:
  endpointMessage: Hello, world!

---
spring.profiles: dev
server:
  port: 8080
file.system.storage:
  path: "J:/JAVA/JTM_fsss"

spring.h2.console.enabled: true
spring.jpa.hibernate.ddl-auto: none

logging:
  level:
    org.springframework.jdbc.core: DEBUG

---
spring.profiles: prod
server:
  port: 9090
file.system.storage:
  path: "J:/JAVA/JTM_fsss"