server:
  port: 8080
file.system.storage:
  path: "J:/JAVA/JTM_fsss"
spring.h2.console.enabled: true
spring.jpa.hibernate.ddl-auto: create-drop
logging:
  level:
    org.springframework.jdbc.core: DEBUG

---
spring.profiles: dev
server:
  port: 8080
file.system.storage:
  path: "J:/JAVA/JTM_fsss"

spring.h2.console.enabled: true
spring.jpa.hibernate.ddl-auto: create-drop

logging:
  level:
    org.springframework.jdbc.core: DEBUG

---
spring.profiles: prod
server:
  port: 9090
file.system.storage:
  path: "J:/JAVA/JTM_fsss"