POST localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "zadanie domowe M3",
  "project": "Kurs Springa",
  "prio": 1
}

###
POST localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "wentylacja garażu",
  "project": "Dom",
  "prio": 1
}

###
GET localhost:8080/api/tasks

###
GET localhost:8080/api/tasks/4

###
DELETE localhost:8080/api/tasks/4

###
PUT localhost:8080/api/tasks/3
Content-Type: application/json

{
  "title": "youtube od Przemka Bykowskiego",
  "description": "dwa kursy - jeden dotyczy SpringBoot'a a drugi Springa",
  "project": "Kurs Springa",
  "prio": 1
}

###
POST localhost:8080/api/tags
Content-Type: application/json

{
  "name": "WAIT"
}

###
